// Rotating quotes about music, learning and practice: [text, author]. Short sayings as commonly attributed.
// If an attribution is wrong, fix it here.
window.QUOTES=[
["Without music, life would be a mistake.","Friedrich Nietzsche"],
["Where words fail, music speaks.","Hans Christian Andersen"],
["Music is the universal language of mankind.","Henry Wadsworth Longfellow"],
["Music can change the world because it can change people.","Bono"],
["Music is the shorthand of emotion.","Leo Tolstoy"],
["Music expresses that which cannot be put into words and that which cannot remain silent.","Victor Hugo"],
["After silence, that which comes nearest to expressing the inexpressible is music.","Aldous Huxley"],
["A painter paints pictures on canvas. But musicians paint their pictures on silence.","Leopold Stokowski"],
["There are two kinds of music, the good, and the bad. I play the good kind.","Louis Armstrong"],
["My music is the spiritual expression of what I am: my faith, my knowledge, my being.","John Coltrane"],
["You've got to learn your instrument. Then you practice, practice, practice. And then, when you finally get up there on the bandstand, forget all that and just wail.","Charlie Parker"],
["It does not matter how slowly you go as long as you do not stop.","Confucius"],
["A journey of a thousand miles begins with a single step.","Laozi"],
["Success is the sum of small efforts, repeated day in and day out.","Robert Collier"],
["Genius is one percent inspiration and ninety-nine percent perspiration.","Thomas Edison"],
["The expert in anything was once a beginner.","Helen Hayes"],
["Great things are done by a series of small things brought together.","Vincent van Gogh"],
["The beautiful thing about learning is that no one can take it away from you.","B.B. King"],
["The more I practice, the luckier I get.","Gary Player"],
["Practice isn't the thing you do once you're good. It's the thing you do that makes you good.","Malcolm Gladwell"],
["Start where you are. Use what you have. Do what you can.","Arthur Ashe"],
["It always seems impossible until it's done.","Nelson Mandela"],
["Perseverance is not a long race; it is many short races one after the other.","Walter Elliot"],
["Fall seven times, stand up eight.","Japanese proverb"],
["Sometimes courage is the quiet voice at the end of the day saying, \"I will try again tomorrow.\"","Mary Anne Radmacher"],
["I am always doing that which I cannot do, in order that I may learn how to do it.","Pablo Picasso"],
["Anyone who stops learning is old, whether at twenty or eighty.","Henry Ford"],
["Music is the divine way to tell beautiful, poetic things to the heart.","Pablo Casals"],
["Music is a world within itself, with a language we all understand.","Stevie Wonder"],
["Energy and persistence conquer all things.","Benjamin Franklin"]
];
